### PR TITLE
fix kodi include path

### PR DESCRIPTION
**Pull request by wsnipex**
should fix the annoying build failures. Tested on linux only

### CODE REVIEW

**Comment by Montellese** [comment]
Hm but why does it work in all the other audioencoders?
* vorbis: https://github.com/xbmc/audioencoder.vorbis/blob/master/src/EncoderVorbis.cpp#L23
* flac: https://github.com/xbmc/audioencoder.flac/blob/master/src/EncoderFlac.cpp#L23
* lame: https://github.com/xbmc/audioencoder.lame/blob/master/src/EncoderLame.cpp#L22

Is there something wrong in the buildsystem that causes this?

**Comment by wsnipex** [comment]
I didn't check, but probably because they have builddir/include somewhere in the include path.
wav only does include_directories(${include_directories(${KODI_INCLUDE_DIR})}). And KODI_INCLUDE_DIR = $prefix/include/kodi

**Comment by Montellese** [comment]
Doesn't look like it:
* vorbis: https://github.com/xbmc/audioencoder.vorbis/blob/master/CMakeLists.txt#L16
* flac: https://github.com/xbmc/audioencoder.flac/blob/master/CMakeLists.txt#L13
* lame: https://github.com/xbmc/audioencoder.lame/blob/master/CMakeLists.txt#L15

But you might be right nonetheless. wav is the only audioencoder which doesn't depend on an external library and the include paths for vorbis, flac and lame probably are $prefix/include so it works by accident.

**Comment by wsnipex** [comment]
yes, that's what I'm thinking as well. Its wrong in all encoders and maybe pvr addons as well.
Anyway, this PR fixes wav, see https://github.com/xbmc/xbmc/pull/7192

**Comment by uNiversaI** [comment]
Indeed after #7192 goes in this fix needs to go into all other addons so that they build and install to correct path, with #7192 in and no fixes to remainder binary addons (audio encoders) all fail except for wav.

**Pull request merged**
